% Matlab startup configuration.
%
% This is the repo-owned startup file. MATLAB boots it through the permanent
% three-line shim at $HOME/MATLAB/startup.m (userpath). Edit this file, never
% the shim (matfunclib-juq.7, spec decision 8).

inoctave = (exist ("OCTAVE_VERSION", "builtin") > 0);
inmatlab = ~inoctave;

USE_PYENV_PYTHON = false;

%% manage warnings

% remap the red close button associated with figure windows, potentially
% preventing MATLAB from becoming unresponsive when closing figures.
% Not needed on newer versions, remove eventually or use verlessthan check.
% set(groot, 'defaultFigureCloseRequestFcn', @(o, ~) delete(o));

% Save the current state of the warnings
originalWarningState = warning;

% Create a cleanup object that will be executed when the function is exited
cleanupObj = onCleanup(@() warning(originalWarningState));

% Suppress warnings (e.g., generated by activating toolboxes)
warning("off", "MATLAB:dispatcher:nameConflict");
warning("off", "MATLAB:rmpath:DirNotFound");
warning("off", "MATLAB_FUNCTION_PATH:manager:toolboxAlreadyActive")

% Suppress the Project path-overlap warning. The startup genpath below puts
% matfunclib folders on the path before any Project opens, so the overlap is
% by design (spec decision 7). Re-asserted after clearvars in FINAL STEPS,
% because the warning-state restore above reverts this copy at script end.
warning("off", "MATLAB:Project:Issues:PathFolderOnMATLABPath")

%% Bootstrap the path-family environment

% mconfig is the one function that sets the path-family env vars
% (MATLAB_HOME_PATH, MATLAB_PROJECT_PATH, and the rest; see mconfig).
% manager lives inside matfunclib, so no manager function can add
% matfunclib to the path first: add the manager folder with one literal,
% then call mconfig. The
% '-begin' puts manager at the front of the path, so a same-named function
% elsewhere on the boot path cannot shadow mconfig; the genpath block below
% re-adds the manager folders at their final position.
addpath(fullfile(getenv('HOME'), 'MATLAB', 'projects', 'matfunclib', ...
   'manager'), '-begin');
cfg = mconfig();

%% Manage desktop versus command-line settigs

if usejava('desktop') % we're in the desktop (also means we're not in octave)

   % When Matlab is started from the desktop app, it inherits the default system
   % PATH, i.e., these should match:
   % [~, default_path] = system('echo -n $PATH');
   % isequal(default_path, getenv('PATH'))

   % Add brew paths to the default system path.
   if ismac()
      setenv('PATH', strjoin({ ...
         '/usr/local/bin', ...
         '/opt/homebrew/bin', ...
         getenv('PATH')}, pathsep));
   end

   % Custom desktop settings
   if inmatlab
      mSettings = settings;

      % Prevent autoformatter from stripping blanks to prevent the cursor from being
      % forced to the first position in indented code blocks (introduced in r2021b)
      if ~isMATLABReleaseOlderThan('R2021b')
         mSettings.matlab.editor.indent.RemoveAutomaticWhitespace.PersonalValue = 0;
      end
      % Make the desktop display larger. A warning is issued on r2023a.
      if isMATLABReleaseOlderThan('R2023a')
         mSettings.matlab.desktop.DisplayScaleFactor.TemporaryValue = 1.2;
      end
   end

   % smartIndentContents (method of class Document) programmatically formats
   % docs = matlab.desktop.editor.getAll
   % smartIndentContents(docs)
   % save(docs)
else
   % Matlab was started from the terminal, which inherits the PATH variable set
   % by the user dotfiles, so there is no need to set PATH.
end

%% Set the user data environment variables

% mconfig owns the MATLAB_* path family. The un-prefixed USER* data vars
% are a separate family (matfunclib-juq.7 non-goal): set them here, not
% in mconfig.

% Define $HOME (system variable) and $HOME/work
HOMEPATH = getenv('HOME');
WORKPATH = fullfile(HOMEPATH, 'work');

% pyenv root
PYENV_ROOT = fullfile(HOMEPATH, '.pyenv', 'versions');

% $HOME/work/projects
setenv('USER_PROJECT_PATH', fullfile(WORKPATH, 'projects'));

setenv('GITHUB_USER_NAME', 'mgcooper');

% user data
setenv('USERDATAPATH',  fullfile(WORKPATH, 'data'));
setenv('USERGISPATH',   fullfile(WORKPATH, 'data', 'GIS'));

% e3sm
setenv('E3SMINPUTPATH',    fullfile(getenv('USERDATAPATH'),'e3sm','input'));
setenv('E3SMOUTPUTPATH',   fullfile(getenv('USERDATAPATH'),'e3sm','output'));
setenv('E3SMTEMPLATEPATH', fullfile(getenv('USERDATAPATH'),'e3sm','templates'));

% Google Drive
% setenv('USERGDRIVEPATH', fullfile(getenv('HOME'), ...
%    'Library/CloudStorage/GoogleDrive-guycooper@g.ucla.edu/My Drive'));

% merra toolbox
setenv('USER_MERRA_PATH', fullfile(getenv('USERDATAPATH'), 'merra2'));

%% Add shared library to path

% Ignored folders - append these to ignorePaths to use
% ignore = {'old_projects'; 'myProjects'};

% Generate a list of all sub-folders under MATLAB_HOME_PATH
subpaths = strsplit( genpath(cfg.MATLAB_HOME_PATH), pathsep );

% Build logical masks to remove all projects and toolboxes from PATH, while
% retaining MATLAB_FUNCTION_PATH to manage projects/toolboxes post-startup
is_project_path = strncmp(...
   subpaths, cfg.MATLAB_PROJECT_PATH, numel(cfg.MATLAB_PROJECT_PATH));

is_toolbox_path = strncmp( ...
   subpaths, cfg.MATLAB_TOOLBOX_PATH, numel(cfg.MATLAB_TOOLBOX_PATH));

is_function_path = strncmp( ...
   subpaths, cfg.MATLAB_FUNCTION_PATH, numel(cfg.MATLAB_FUNCTION_PATH));

% Remove all projects/toolboxes from PATH, except MATLAB_FUNCTION_PATH
subpaths = subpaths(~(is_project_path | is_toolbox_path) | is_function_path);

% Remove ignored folders.
removePaths = {'.git'; '.svn'; '.'; '..'; };
keep = @(folders, ignore) cellfun('isempty', (strfind(folders, ignore)));

% Custom ignores for octave compatibility: one shared list, from
% octaveignorepaths. mconfig has run, so the helper's getenv reads
% match cfg.
if inoctave
   removePaths = [removePaths; octaveignorepaths()];
end

for m = 1:numel(removePaths)
   subpaths = subpaths(keep(subpaths, removePaths{m}));
end

% Rebuild the path string
subpaths = strcat(subpaths, pathsep);
subpaths = horzcat(subpaths{:});

% Add the paths to the path
addpath(subpaths, '-end');

% Add these paths to the top to ensure they are not shadowed by built-ins
addpath(fullfile(cfg.MATLAB_FUNCTION_PATH, 'libstats'), '-begin');

%% Figure defaults

% groot settings apply to low-level properties and therefore low-level functions
% such as 'line', but may not apply to high-level functions such as 'plot'
% (e.g., defaultAxesBox off). However, if 'hold on' is used prior to plot, these
% properties apply. So, in custom plotting functions, begin with 'hold on'.

set(groot                                                      , ...
   'defaultAxesFontName'            ,  'SF Pro Text'           , ...
   'defaultTextFontName'            ,  'SF Pro Text'           , ...
   'defaultTextInterpreter'         ,  'Tex'                   , ...
   'defaultAxesFontSize'            ,  16                      , ...
   'defaultTextFontSize'            ,  16                      , ...
   'DefaultAxesFontUnits'           ,  'points'                , ...
   'DefaultTextFontUnits'           ,  'points'                , ...
   'defaultLineLineWidth'           ,  2                       , ...
   'defaultAxesLineWidth'           ,  1                       , ...
   'defaultPatchLineWidth'          ,  1                       , ...
   'defaultAxesColor'               ,  'w'                     , ...
   'DefaultAxesXColor'              ,  [0.15 0.15 0.15]        , ...
   'DefaultAxesYColor'              ,  [0.15 0.15 0.15]        , ...
   'defaultFigureColor'             ,  'w'                     , ...
   'defaultAxesBox'                 ,  'off'                   , ...
   'DefaultAxesTickLength'          ,  [0.015 0.02]            , ...
   'defaultAxesTickDir'             ,  'out'                   , ...
   'defaultAxesXGrid'               ,  'on'                    , ...
   'defaultAxesYGrid'               ,  'on'                    , ...
   'defaultAxesXMinorGrid'          ,  'off'                   , ...
   'defaultAxesXMinorTick'          ,  'on'                    , ...
   'defaultAxesYMinorGrid'          ,  'off'                   , ...
   'defaultAxesYMinorTick'          ,  'on'                    , ...
   'defaultAxesTickDirMode'         ,  'manual'                , ...
   'defaultAxesMinorGridAlpha'      ,  0.075                   , ...
   'defaultAxesMinorGridLineStyle'  ,  '-'                     );

% xminorgridmode
if inmatlab
   set(groot                                                   , ...
      'defaultAxesXMinorGridMode'      ,  'manual'             , ...
      'defaultAxesYMinorGridMode'      ,  'manual'             , ...
      'defaultAxesXMinorTickMode'      ,  'manual'             , ...
      'defaultAxesYMinorTickMode'      ,  'manual'             );

   beep off
end
%% Environment configuration

format short % careful with shortG, it truncates to 5 digits
format compact % use pi to see different formats: pi

%% activate toolboxes and projects

% active toolboxes
default_toolboxes = {};

% default_toolboxes = {
%    'BrewerMap', 'CubeHelix', 'mpm', 'CDT', 'arctic-mapping-tools', ...
%    'antarctic-mapping-tools', ...
%    };

for n = 1:numel(default_toolboxes)
   toolbox_name = default_toolboxes{n};
   try
      if strcmp(toolbox_name, 'spatial')
         activate(toolbox_name, 'except', {'exactremap'})
      else
         activate(toolbox_name)
      end
   catch ME
   end
end

% add projects to the path
% default_projects = {'bfra', 'merra2', 'graceGapFill', 'exactremap', 'groupstats'};
default_projects = {};
for n = 1:numel(default_projects)
   project_name = default_projects{n};
   try
      activate(project_name, silent=true, asproject=true);
   catch ME
   end
end

% open the active project if we're in the desktop
if usejava('desktop') && inmatlab
   % set updatefiles=false because on startup, no files are open.
   % this ensures workon opens the activefiles associated w/the active project.
   workon(getactiveproject(), 'updatefiles', false);
end

% cd to ~/MATLAB if we're in octave
if inoctave
   disp('going home')
   cd(getenv('MATLAB_HOME_PATH'))
end

%% Python configuration

if inmatlab == true && USE_PYENV_PYTHON == true && isfolder(PYENV_ROOT)

   pyExe = newestSupportedPyenvPython(PYENV_ROOT);

   if strlength(pyExe) > 0
      pe = pyenv;
      if pe.Status == "NotLoaded"
         pyenv("Version", pyExe);
      end
   end
end

%% Launch toolboxes
if inmatlab
   try
      ismap(gca);
   catch
   end

   try
      statsOptions = statset();
   catch
   end

   try
      curveFitOptions = fitoptions();
   catch
   end

   try
      optimOptions = optimoptions("fminunc");
   catch
   end

   try
      imread('ngc6543a.jpg');
   catch
   end
end

%% FINAL STEPS

% clear vars but not the screen b/c it deletes error msgs
clearvars
close all

% Re-assert the Project path-overlap suppression for the whole session. The
% clearvars above destroyed the onCleanup object, which restored the saved
% warning state and reverted the copy set in the manage-warnings section.
warning("off", "MATLAB:Project:Issues:PathFolderOnMATLABPath")

% don't forget - commented out to reduce context window bloat
% disp('BE GRATEFUL')

%% Notes

% default font is Monospaced. Some good ones include:
% fontName = 'Verdana';
% fontName = 'avantgarde';
% fontName = 'BitstreamSansVeraMono';
% fontName = 'Helvetica';
% fontName = 'Source Sans Pro' (nice and compact also if bold)

function pyExe = newestSupportedPyenvPython(pyenvRoot)

   if ~isMATLABReleaseOlderThan("R2024b")
      supported = ["3.12", "3.11", "3.10", "3.9"];
   elseif ~isMATLABReleaseOlderThan("R2023b")
      supported = ["3.11", "3.10", "3.9"];
   elseif ~isMATLABReleaseOlderThan("R2022b")
      supported = ["3.10", "3.9", "3.8"];
   elseif ~isMATLABReleaseOlderThan("R2022a")
      supported = ["3.9", "3.8"];
   elseif ~isMATLABReleaseOlderThan("R2021b")
      supported = ["3.9", "3.8", "3.7"];
   elseif ~isMATLABReleaseOlderThan("R2021a")
      supported = ["3.8", "3.7"];
   else
      supported = "3.8";
   end

   pyExe = "";
   for version = supported
      matches = dir(fullfile(pyenvRoot, version + "*", "bin", "python"));
      matches = matches(~[matches.isdir]);

      if ~isempty(matches)
         pyExe = fullfile(matches(1).folder, matches(1).name);
         return
      end
   end
end
