
function bearer=create_new_bearer(email,password,client_id,client_secret)


opts = weboptions('ContentType', 'json');
url = 'https://api.netatmo.com/oauth2/token';
fieldName1 = 'Host';        fieldValue1 = 'api.netatmo.com';
fieldName2 = 'Content-Type';fieldValue2 = 'application/x-www-form-urlencoded;charset=UTF-8';
fieldName3 = 'grant_type';  fieldValue3 = 'password';
fieldName4 = 'username';    fieldValue4 = email;
fieldName5 = 'password';    fieldValue5 = password;
fieldName6 = 'client_id';   fieldValue6 = client_id;
fieldName7 = 'client_secret'; fieldValue7 = client_secret;
fieldName8 = 'scope';       fieldValue8 = 'read_station';

response = webwrite(url, fieldName1, fieldValue1,...
    fieldName2,fieldValue2,...
    fieldName3, fieldValue3,...
    fieldName4, fieldValue4,...
    fieldName5, fieldValue5,...
    fieldName6, fieldValue6,...
    fieldName7, fieldValue7,...
    fieldName8, fieldValue8,...
    opts);

bearer=response.access_token;