function parser = createParser( ...
   functionName, ...
   required_args,required_validations, ...
   optional_args, optional_defaults, optional_validations, ...
   parameter_args, parameter_defaults)

% would be good to use argument list
% p = inputParser;
% p.

parser = inputParser;
parser.FunctionName = functionName;

% cycle over default parser options - KeepUnmatched etc.

for n = 1:numel(parseropts)
	parser.parseropts{n}   = false;
end

for n = 1:numrequired

   parser.addRequired( ...
      required_args{n}, ...
      required_validations{n} ...
      );
end

for n = 1:numoptional

   parser.addOptional( ...
      optional_args{n}, ...
      optional_defaults{n}, ...
      optional_validations{n} ...
      );
end

for n = 1:numparameter

   parser.addParameter( ...
      parameter_args{n}, ...
      parameter_defaults{n}, ...
      parameter_validations{n} ...
      );
end