function matlabType = nctype2mat(xtype)
   % Map NetCDF data types to MATLAB data types

   persistent typeMap
   if isempty(typeMap)
      typeMap = containers.Map(...
         {'NC_FLOAT', 'NC_DOUBLE', 'NC_INT64', 'NC_UINT64', 'NC_INT', ...
         'NC_UINT', 'NC_SHORT', 'NC_USHORT', 'NC_BYTE', 'NC_UBYTE', ...
         'NC_CHAR', 'NC_STRING', 'NC_VLEN'}, ...
         {'single', 'double', 'int64', 'uint64', 'int32', ...
         'uint32', 'int16', 'uint16', 'int8', 'uint8', ...
         'char', 'string', 'cell'} ...
         );
   end

   matlabType = typeMap(xtype);
end
