function S = makemapspec(geometry,varargin)
   %MAKEMAPSPEC Make map specification structure for mapshow
   %
   %  S = MAKEMAPSPEC(geometry);
   %  S = MAKEMAPSPEC(geometry,'numfeatures',numfeatures);
   %
   % See also: geostructinit, geomap

   parser = inputParser();
   parser.FunctionName = mfilename;
   parser.CaseSensitive = false;
   parser.KeepUnmatched = true;
   parser.addRequired('geometry', @ischar);
   parser.addParameter('numfeatures', 1, @isnumeric);
   parser.parse(geometry, varargin{:});
   numfeatures = parser.Results.numfeatures;

   c = distinguishable_colors(numfeatures);
   for n = 1:numfeatures
      switch lower(geometry)

         case 'polygon'
            S(n) = makesymbolspec('Polygon', { ...
               'Default', ...
               'FaceColor', 'none', ...
               'EdgeColor', c(n, :), ...
               'LineWidth', 1 ...
               } );

         case 'point'
            S(n) = makesymbolspec('Point', { ...
               'Default', ...
               'Marker', 'o', ...
               'MarkerSize', 6, ...
               'MarkerFaceColor', c(n, :),  ...
               'MarkerEdgeColor', 'none' ...
               } );

         case 'line'
            S(n) = makesymbolspec('Line',{ ...
               'Default', ...
               'Color', c(n, :), ...
               'LineWidth', 1 ...
               } );
      end
   end
end
