This is just an idea. It is based on Julia's Project.toml format
https://pkgdocs.julialang.org/v1/toml-files/

authors = ["Some One <someone@email.com>",
           "Foo Bar <foo@bar.com>"]

name = "Example"

version = 0.1.0

uuid = "7876af07-990d-54b4-ab0e-23690620f79a"
Note: It is recommended that UUIDs.uuid4() is used to generate random UUIDs.

[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"


Below here is from Manifest.toml

julia_version = "1.8.2"
manifest_format = "2.0"
project_hash = "4d9d5b552a1236d3c1171abf88d59da3aaac328a"