function varargout = shortcut_tricks(varargin)
%MATLAB_TRICKS matlab tips and tricks

% if called with no input, open this file
if nargin == 0; open(mfilename('fullpath')); return; end

% just in case this is called by accident
narginchk(0,0)

%%

% TLDR: Preferences -> Matlab -> Keyboard -> Shortcuts -> (make changes) ->
% Active Settings Drop Down -> Save As
% Once it's saved, it will be available in the dropdown, but if moved, its not
% available there anymore, so instead, open the drop down menu and Save As again
% to move it.

% CustomMacSet.xml is the auto filename generated by the keyboard preferences
% dialog save as. I put it under source control in matfunclib/templates, but the
% default location is ~/Library/Application Support/MathWorks/MATLAB/R2022b. It
% was originally in matfunclib/. When I moved it to templates/ , matlab did not
% find it, then i moved it back, and it was available in the drop down menu of
% the keyboard prefs, so I resaved it as
% matfunclib/templates/CustomMacSetWork.xml and renamed the one in tmeplates/ to
% CustomMacSetPersonal.xml

% I am not sure why, but it seems to have been overridden. 


%%

% set cmd-F to Find-Replace:
% - open prefs/keyboard, serach for replace, set to cmd-F
% - remove cmd-F from find

%% Shortcuts

% HOW TO KEYBOARD SHORTCUT TO VARIABLE WINDOW WHEN 

% programmatically create favorites:
% https://www.mathworks.com/matlabcentral/answers/411846-how-to-create-favorites-by-code-command-window

% cmd-A then cmd-I to quickly apply smart indent to entire document

% in HOME, see Favorites, create and add to quick access toolbar
% i looked everywhere and could not find a way to assign a keyboard shortcut to
% the quick access shortcuts, though

% cmd-0 sends cursor to command window
% shift-cmd-0 sends it back to the editor
% example: writing a for loop you want n=1 right away, this way you don't need
% to move to the mouse and click on the cmd wdw and type n=1

% end/start of line           cmd-arrow 
% run current selection       shift-enter
% comment line                cmd-/
% uncomment line              cmd-T
% cursor to cmd window        cmd-0
% cursor to editor            shift-cmd-0
% page open tabs              ctl-page up/down (works for editor, help, and variable tabs)
% 



% cmd-arrow moves to end or beginning of current line, so I want this to 

% MAC
% cmd-tab (keep cmd held down) to move through open apps
% shift-cmd-[ moves through open tabs in safari