
% for some reason the code below returns data for only the first day oct
% 14, and only for a small area, not the full time period and spatial
% bounding box specified in the api call. Instead, download the data
% manually here:
% https://nsidc.org/data/atl06



%%
%   % SMAP L3 Radiometer Global Daily 36 km EASE-Grid Soil Moisture,
%   % Version 5, GeoTIFF reformatting, spatial subsetting*, parameter
%   % subsetting, and Geographic reprojection for all data collected
%   % 2008-06-06 to 2018-06-07 over Colorado:
%        ['https://n5eil02u.ecs.nsidc.org/egi/request?' ...
%             'short_name=SPL3SMP' ...
%             '&version=005' ...
%             '&format=GeoTIFF' ...
%             '&time=2018-06-06,2018-06-07' ...
%             '&bounding_box=-109,37,-102,41' ...
%             '&bbox=-109,37,-102,41' ...
%             '&Coverage=/Soil_Moisture_Retrieval_Data_AM/soil_moisture' ...
%             '&projection=Geographic' ...
%             '&email=yes' ...
%             '&token=75E5CEBE-6BBB-2FB5-A613-0368A361D0B6'];

%   Example 2 
%   ---------
%   % ATLAS/ICESat-2 L3A Land Ice Height, Version 1, with variable
%   % subsetting % for all data over the Barnes Ice Cap using an uploaded
%   % shapefile* of the % ice cap boundary:
%         ['curl -O -J -F "shapefile=@barnes_shapefile.zip" ' ...
%             '"https://n5eil02u.ecs.nsidc.org/egi/request?' ...
%             'short_name=ATL06' ...
%             '&version=001' ...
%             '&polygon=-74.886,69.408,-71.681,69.408,-71.681,70.62,-74.886,70.62,-74.886,69.408' ...
%             '&coverage=/gt1l/land_ice_segments/h_li,/gtl1/land_ice_segments/latitude,/gtl1/land_ice_segments/longitude,/gtlr/land_ice_segments/h_li,/gtlr/land_ice_segments/latitude,/gtlr/land_ice_segments/longitude,/gt2l/land_ice_segments/h_li,/gt21/land_ice_segments/latitude,/gt21/land_ice_segments/longitude,/gt2r/land_ice_segments/h_li,/gt2r/land_ice_segments/latitude,/gt2r/land_ice_segments/longitude,/gt31/land_ice_segments/h_li,/gt31/land_ice_segments/latitude,/gt31/land_ice_segments/longitude,/gt3r/land_ice_segments/h_li,/gt3r/land_ice_segments/latitude,/gt3r/land_ice_segments/longitude,/quality_assessment' ...
%             '&email=yes' ...
%             '&token=75E5CEBE-6BBB-2FB5-A613-0368A361D0B6"'];
        
% list of available short names
% short_names = {'SPL3SMP'}; % add the rest
    
% user needs curl, and matlab needs to know where curl is
% which curl

% if no token is given, issue instructions for how to make one:
% curl -X POST --header "Content-Type: application/xml" -d
% '<token><username>earthdata_login_user_name</username><password>earthdata_login_password</password><client_id>NSIDC_client_id</client_id><user_ip_address>your_origin_ip_address</user_ip_address>
% </token>' https://api.echo.nasa.gov/echo-rest/tokens

clean

%%
uname           =   'mguycooper';
pword           =   '';
options         =   weboptions('Username',uname,'Password',pword, ...
                        'Timeout',2000);
                    
basestr         =   'https://n5eil02u.ecs.nsidc.org/egi/request?';
str1            =   'short_name=';
str2            =   '&version=';
str3            =   '&format=';
str4            =   '&time=';
str5            =   '&bounding_box=';
str6            =   '&bbox=';
str7            =   '&Coverage=';
str8            =   '&projection=';
str9            =   '&email=';
str0            =   '&token=';

short_name      =   'ATL06';
version         =   '001';
format          =   'h5';
time            =   '2018-10-14,2018-10-16';
bounding_box    =   '-80,58,-10,82';
bbox            =   '-80,58,-10,82';
coverage        =   ['/gt1l/land_ice_segments/h_li,' ...
                    '/gtl1/land_ice_segments/latitude,' ...
                    '/gtl1/land_ice_segments/longitude,' ...
                    '/gtlr/land_ice_segments/h_li,' ...
                    '/gtlr/land_ice_segments/latitude,' ...
                    '/gtlr/land_ice_segments/longitude,' ...
                    '/gt2l/land_ice_segments/h_li,' ...
                    '/gt21/land_ice_segments/latitude,' ...
                    '/gt21/land_ice_segments/longitude,' ...
                    '/gt2r/land_ice_segments/h_li,' ...
                    '/gt2r/land_ice_segments/latitude,' ...
                    '/gt2r/land_ice_segments/longitude,' ...
                    '/gt31/land_ice_segments/h_li,' ...
                    '/gt31/land_ice_segments/latitude,' ...
                    '/gt31/land_ice_segments/longitude,' ...
                    '/gt3r/land_ice_segments/h_li,' ...
                    '/gt3r/land_ice_segments/latitude,' ...
                    '/gt3r/land_ice_segments/longitude,/' ...
                    'quality_assessment'];
projection      =   'Geographic';
email           =   'yes';
token           =   '288C032D-5C66-DDD7-24C3-4E7698A4E2DA'; % note: this is my token


str             =   [basestr str1 short_name str2 version str3 format ...
                    str4 time str5 bounding_box str6 bbox str7 coverage ...
                    str8 projection str0 token];
    
websave('test2.zip',str,options);

%% try removing version, coverage, etc.

basestr         =   'https://n5eil02u.ecs.nsidc.org/egi/request?';
str1            =   'short_name=';
str2            =   '&time=';
str3            =   '&bounding_box=';
str4            =   '&bbox=';
str5            =   '&Coverage=';
str6            =   '&token=';

% set answers
short_name      =   'ATL06';
% time            =   '2018-10-14,2019-06-10';
time            =   '2018-10-15,2018-10-16';
bounding_box    =   '-80,58,-10,82'; % west south east north
bbox            =   '-80,58,-10,82';
coverage        =   ['/gt1l/land_ice_segments/h_li,' ...
                    '/gtl1/land_ice_segments/latitude,' ...
                    '/gtl1/land_ice_segments/longitude,' ...
                    '/gtlr/land_ice_segments/h_li,' ...
                    '/gtlr/land_ice_segments/latitude,' ...
                    '/gtlr/land_ice_segments/longitude,' ...
                    '/gt2l/land_ice_segments/h_li,' ...
                    '/gt21/land_ice_segments/latitude,' ...
                    '/gt21/land_ice_segments/longitude,' ...
                    '/gt2r/land_ice_segments/h_li,' ...
                    '/gt2r/land_ice_segments/latitude,' ...
                    '/gt2r/land_ice_segments/longitude,' ...
                    '/gt31/land_ice_segments/h_li,' ...
                    '/gt31/land_ice_segments/latitude,' ...
                    '/gt31/land_ice_segments/longitude,' ...
                    '/gt3r/land_ice_segments/h_li,' ...
                    '/gt3r/land_ice_segments/latitude,' ...
                    '/gt3r/land_ice_segments/longitude,/' ...
                    'quality_assessment'];
token           =   '288C032D-5C66-DDD7-24C3-4E7698A4E2DA'; % note: this is my token

str             =   [basestr str1 short_name str2 time str3 bounding_box ...
                    str4 bbox  str5 coverage str6 token];
    
websave('data.zip',str,options);

% note = this works. Not sure whe 

%%
% 
% info = h5info(['C:\Users\mcooper\Dropbox\CODE\MATLAB\GREENLAND\IceSat2\' ...
%                 'data\ATL06_20190223001901_08640202_001_01.h5']);
%             

%%
%                 '&time=2018-10-14,2018-10-16' ...
%                 '&bounding_box=-80,58,-10,82' ...
%                 '&bbox=-80,58,-10,82' ...
                
str     =   [   basestr ...
                'short_name=ATL06' ...
                '&version=001' ...
                '&format=h5' ...
                '&coverage=/gt1l/land_ice_segments/h_li,' ...
                '/gtl1/land_ice_segments/latitude,' ...
                '/gtl1/land_ice_segments/longitude,' ...
                '/gtlr/land_ice_segments/h_li,' ...
                '/gtlr/land_ice_segments/latitude,' ...
                '/gtlr/land_ice_segments/longitude,' ...
                '/gt2l/land_ice_segments/h_li,' ...
                '/gt21/land_ice_segments/latitude,' ...
                '/gt21/land_ice_segments/longitude,' ...
                '/gt2r/land_ice_segments/h_li,' ...
                '/gt2r/land_ice_segments/latitude,' ...
                '/gt2r/land_ice_segments/longitude,' ...
                '/gt31/land_ice_segments/h_li,' ...
                '/gt31/land_ice_segments/latitude,' ...
                '/gt31/land_ice_segments/longitude,' ...
                '/gt3r/land_ice_segments/h_li,' ...
                '/gt3r/land_ice_segments/latitude,' ...
                '/gt3r/land_ice_segments/longitude,' ...
                '/quality_assessment' ...
                '&token=288C032D-5C66-DDD7-24C3-4E7698A4E2DA'];
            
websave('test2.zip',str,options);



            