classdef testBlankTextHelpers < matlab.unittest.TestCase

   methods (TestClassSetup)
      function addProjectToPath(testCase)
         import matlab.unittest.fixtures.PathFixture

         testFile = mfilename("fullpath");
         testFolder = fileparts(testFile);
         libraryFolder = fileparts(testFolder);
         projectFolder = fileparts(libraryFolder);
         testCase.applyFixture(PathFixture(projectFolder, ...
            "IncludingSubfolders", true));
      end
   end

   methods (Test)
      function testIsblanktextTrueCases(testCase)
         testCase.verifyPredicate(@isblanktext, { ...
            '', ...
            char.empty(0, 0), ...
            "", ...
            string.empty(0, 0)}, true);
      end

      function testIsblanktextFalseCases(testCase)
         testCase.verifyPredicate(@isblanktext, { ...
            'abc', ...
            "abc", ...
            missing, ...
            ["", ""], ...
            [], ...
            {}, ...
            0}, false);
      end

      function testIsscalartextPreservesLegacyBlankCharBehavior(testCase)
         testCase.verifyTrue(isscalartext(''));
         testCase.verifyTrue(isscalartext(""));
         testCase.verifyFalse(isscalartext(string.empty(0, 0)));
      end

      function testIsblankpartTreatsBlankTextAndEmptyCellsAsBlank(testCase)
         testCase.verifyPredicate(@isblankpart, { ...
            '', ...
            "", ...
            string.empty(0, 0), ...
            {}}, true);
      end

      function testIsblankpartRejectsNonblankParts(testCase)
         testCase.verifyPredicate(@isblankpart, { ...
            'abc', ...
            "abc", ...
            {'abc'}, ...
            0}, false);
      end
   end

   methods (Access = private)
      function verifyPredicate(testCase, predicate, values, expected)
         returned = cellfun(predicate, values);
         testCase.verifyEqual(returned, repmat(expected, size(returned)));
      end
   end
end
