function dispsubtightplot
% Input arguments (defaults exist):
disp([                                  newline ...
        'gap: [vertical horizontal]'    newline ...
        'marh: [lower uppper]'          newline ...
        'marw: [left right]'            newline ... 
                                        ]);