function spec = mapspec(geometry,numcolors)
    
c = distinguishable_colors(num);
for i = 1:num
   switch geometry
      case 'polygon'
          spec(i) = makesymbolspec('Polygon',{'Default',          ...
                      'FaceColor','none',                         ...
                      'EdgeColor',c(i,:),                         ...
                      'LineWidth',1});
      case 'point'
          spec(i) = makesymbolspec('Point',{'Default',            ...
                      'Marker','o',                               ...
                      'MarkerSize',6,                             ...
                      'MarkerFaceColor',c(i,:),                   ...
                      'MarkerEdgeColor','none'});
      case 'line'
          spec(i) = makesymbolspec('Line',{'Default',             ...
                      'Color',c(i,:),                             ...
                      'LineWidth',1});
   end
end


