function location = parseGraphicsLocation(varargin)

   location = parseoptarg(varargin, { ...
      'closest', 'Closest', ...
      'ne', 'NE', 'northeast', 'northEast', 'NorthEast', ...
      'se', 'SE', 'southeast', 'southEast', 'SouthEast', ...
      'nw', 'NW', 'northwest', 'northWest', 'NorthWest', ...
      'sw', 'SW', 'southwest', 'southWest', 'SouthWest', ...
      'n', 'N', 'north', 'North', ...
      's', 'S', 'south', 'South', ...
      'e', 'E', 'east', 'East', ...
      'w', 'W', 'west', 'West', ...
      }, ...
      'northeast'); % default = 'northeast'
end
