classdef testReleaseOptions < matlab.unittest.TestCase
   %TESTRELEASEOPTIONS Test what the release task would package.
   %
   % releasefile and the buildfile release task read
   % tbx.internal.releaseoptions. These cases read the same options and
   % check what a release would ship. Reading the options writes
   % nothing; no case packages a toolbox, so the suite is CI-safe.
   %
   % The template ships no root .prj (its Project is generated by
   % manager's createMatlabProject when wanted), so these cases pin the
   % folder-construction fallback: options built from toolbox/ with the
   % injectively encoded "<encoded>-toolbox" identifier.

   properties
      % The options a release would package, read once per class.
      Opts

      % Project root (the folder holding buildfile.m), derived from this
      % file so the suite runs from any folder.
      Root
   end

   methods (TestClassSetup)
      function readPackagingOptions(testCase)
         import matlab.unittest.fixtures.PathFixture

         testCase.Root = string(fileparts(fileparts( ...
            mfilename('fullpath'))));

         % ToolboxOptions can open a MATLAB Project when it reads a
         % .prj (a stamped project may carry one), and a Project
         % manages the search path. Save the path and close any Project
         % this read opens, so later suites see the state they started
         % with (shared suite helper).
         saved = path();
         testCase.addTeardown(@() path(saved));
         testCase.addTeardown(@() closetestproject(testCase.Root));

         % Read what the release reads, through the shipped namespace.
         testCase.applyFixture(PathFixture( ...
            fullfile(testCase.Root, "toolbox")));
         testCase.Opts = tbx.internal.releaseoptions(testCase.Root);
      end
   end

   methods (Test)
      function testVersionComesFromVersionTxt(testCase)
         % The version is pinned from version.txt (leading "v"
         % stripped), so a release cannot ship a disagreeing version.
         % The file lives inside the shipped toolbox/ folder so an
         % installed package carries its own version source.
         returned = string(testCase.Opts.ToolboxVersion);
         expected = erase(strtrim(string(fileread(fullfile( ...
            testCase.Root, 'toolbox', 'version.txt')))), "v");
         testCase.verifyEqual(returned, expected)
      end

      function testFallbackIdentifierIsDeterministic(testCase)
         % The no-task fallback derives the identifier from the project
         % name through the documented injective encoding, so repeated
         % releases upgrade in place and the assertion holds in stamped
         % projects whatever their names.
         % Rejoin base and extension so dotted stamped names derive
         % whole, matching the implementation's derivation.
         [~, rootBase, rootExt] = fileparts(testCase.Root);
         projectname = string(rootBase) + string(rootExt);
         returned = string(testCase.Opts.Identifier);
         expected = encodeExpected(projectname) + "-toolbox";
         testCase.verifyEqual(returned, expected)
      end

      function testEveryPackagedFileExists(testCase)
         % A packaged entry that is not on disk fails the release late,
         % at the packaging step, rather than here.
         files = string(testCase.Opts.ToolboxFiles);
         returned = files(~isfile(files) & ~isfolder(files));
         expected = strings(0, 1);
         testCase.verifyEqual(returned(:), expected)
      end

      function testEveryPackagedFileIsInsideTheToolboxFolder(testCase)
         % Packaging a file from outside toolbox/ would ship repository
         % scaffolding to an installing user.
         toolboxfolder = fullfile(testCase.Root, "toolbox");
         files = string(testCase.Opts.ToolboxFiles);
         returned = files(~startsWith(files, toolboxfolder));
         expected = strings(0, 1);
         testCase.verifyEqual(returned(:), expected)
      end

      function testRepositoryScaffoldingIsNotPackaged(testCase)
         % Source control data, packaging projects, and built releases
         % have no use to an installing user.
         files = string(testCase.Opts.ToolboxFiles);
         returned = nnz(endsWith(files, ".mltbx") ...
            | endsWith(files, ".prj") ...
            | contains(files, filesep + ".git"));
         expected = 0;
         testCase.verifyEqual(returned, expected)
      end

      function testOutputFileIsVersionedUnderRelease(testCase)
         % The .mltbx lands in release/ with the version in its name,
         % so successive releases never overwrite each other.
         outputfile = string(testCase.Opts.OutputFile);
         v = strtrim(string(fileread(fullfile(testCase.Root, ...
            'toolbox', 'version.txt'))));

         returned = startsWith(outputfile, ...
            fullfile(testCase.Root, "release") + filesep);
         testCase.verifyTrue(returned)

         returned = contains(outputfile, v);
         testCase.verifyTrue(returned)

         returned = endsWith(outputfile, ".mltbx");
         testCase.verifyTrue(returned)
      end

      function testHiddenFilesAreNotPackaged(testCase)
         % macOS writes .DS_Store into any folder the Finder displays.
         % The seeded fixture lives in an owned temporary root, never
         % in the checkout, so an interrupted run leaves no repository
         % state behind.
         import matlab.unittest.fixtures.TemporaryFolderFixture
         tmp = testCase.applyFixture(TemporaryFolderFixture);
         root = fullfile(string(tmp.Folder), "hiddenproj");
         mkdir(fullfile(root, "toolbox"))
         writelines("function y = hp_fun(x), y = x; end", ...
            fullfile(root, "toolbox", "hp_fun.m"));
         writelines("v0.1.0", fullfile(root, "toolbox", "version.txt"));
         seeded = fullfile(root, "toolbox", ".DS_Store");
         writelines("seeded by testReleaseOptions", seeded);

         opts = tbx.internal.releaseoptions(root);
         files = string(opts.ToolboxFiles);

         testCase.assertTrue(isfile(seeded), ...
            'The fixture must exist for this check to mean anything.');

         returned = nnz(contains(files, ".DS_Store"));
         expected = 0;
         testCase.verifyEqual(returned, expected)

         % The filter must not drop the real code file with the hidden
         % one.
         returned = any(endsWith(files, "hp_fun.m"));
         testCase.verifyTrue(returned)
      end

      function testGettingStartedGuideIsConfigured(testCase)
         % The guide is what MATLAB opens after an install; the
         % fallback must configure it when the conventional file
         % exists, not merely package it.
         guide = string(testCase.Opts.ToolboxGettingStartedGuide);
         testCase.assertNotEmpty(guide)

         returned = endsWith(guide, "gettingStarted.mlx");
         testCase.verifyTrue(returned)

         returned = ismember(guide, string(testCase.Opts.ToolboxFiles));
         expected = true;
         testCase.verifyEqual(returned, expected)
      end

      function testInvalidPrjFallsBackToFolderOptions(testCase)
         % A root .prj that is not a Project packaging file (the old
         % hand-made stub shape) raises NotValidToolboxPRJ, which must
         % select the folder fallback instead of aborting.
         import matlab.unittest.fixtures.TemporaryFolderFixture
         tmp = testCase.applyFixture(TemporaryFolderFixture);
         root = makeFallbackRoot(tmp.Folder, "stubproj");
         writelines([ ...
            "<?xml version=""1.0"" encoding=""UTF-8""?>"; ...
            "<MATLABProject xmlns=""http://www.mathworks.com/" + ...
            "MATLABProjectFile"" version=""1.0""/>"], ...
            fullfile(root, "Stubproj.prj"));

         opts = tbx.internal.releaseoptions(root);

         returned = string(opts.Identifier);
         expected = "stubproj-toolbox";
         testCase.verifyEqual(returned, expected)
      end

      function testRootVersionLayoutIsRefused(testCase)
         % A root version.txt is refused whether it is the only copy
         % (metadata an install cannot see) or a duplicate of the
         % shipped one (a second apparent source editing would not
         % change).
         import matlab.unittest.fixtures.TemporaryFolderFixture
         tmp = testCase.applyFixture(TemporaryFolderFixture);
         root = makeFallbackRoot(tmp.Folder, "rootverproj");
         movefile(fullfile(root, "toolbox", "version.txt"), ...
            fullfile(root, "version.txt"))

         testCase.verifyError( ...
            @() tbx.internal.releaseoptions(root), ...
            "tbx:releaseoptions:versionOutsideShippedFolder")

         % The duplicate layout: both files present is refused too.
         writelines("v9.9.9", fullfile(root, "toolbox", "version.txt"));
         testCase.verifyError( ...
            @() tbx.internal.releaseoptions(root), ...
            "tbx:releaseoptions:versionOutsideShippedFolder")
      end

      function testNonAsciiProjectNameIsRefused(testCase)
         % Two-hex escapes are unambiguous only for single-byte code
         % units, so a non-ASCII name is refused rather than encoded
         % ambiguously.
         import matlab.unittest.fixtures.TemporaryFolderFixture
         tmp = testCase.applyFixture(TemporaryFolderFixture);
         root = makeFallbackRoot(tmp.Folder, "pr" + char(233) + "jet");

         testCase.verifyError( ...
            @() tbx.internal.releaseoptions(root), ...
            "tbx:releaseoptions:nonAsciiProjectName")
      end

      function testPlainProjectFallsBackToFolderOptions(testCase)
         % projectfile() creates a real MATLAB Project with no embedded
         % Package Toolbox task; reading its .prj raises
         % NO_TOOLBOX_TASK, which must select the folder fallback
         % instead of aborting the release.
         import matlab.unittest.fixtures.TemporaryFolderFixture
         tmp = testCase.applyFixture(TemporaryFolderFixture);
         root = fullfile(string(tmp.Folder), "plainproj");
         mkdir(fullfile(root, "toolbox"))
         writelines("function y = pp_fun(x), y = x; end", ...
            fullfile(root, "toolbox", "pp_fun.m"));
         writelines("v0.2.0", fullfile(root, "toolbox", "version.txt"));
         close(matlab.project.createProject( ...
            "Name", "plainproj", "Folder", root));
         testCase.addTeardown(@() closetestproject(root));

         opts = tbx.internal.releaseoptions(root);

         returned = string(opts.Identifier);
         expected = "plainproj-toolbox";
         testCase.verifyEqual(returned, expected)

         returned = string(opts.ToolboxVersion);
         expected = "0.2.0";
         testCase.verifyEqual(returned, expected)
      end

      function testFallbackEncodesIdentifierAndReadsRootVersion(testCase)
         % A project name with characters identifiers reject must
         % encode to a legal identifier, distinct names must never
         % share one (the encoding is injective), and the version must
         % come from the given root, not from this template's.
         import matlab.unittest.fixtures.TemporaryFolderFixture
         tmp = testCase.applyFixture(TemporaryFolderFixture);

         makeRoot = @(name) makeFallbackRoot(tmp.Folder, name);
         optsUnderscore = tbx.internal.releaseoptions( ...
            makeRoot("my_project"));
         optsDot = tbx.internal.releaseoptions(makeRoot("my.project"));

         % The documented encoding: "_" is hex 5f, "." is hex 2e.
         returned = string(optsUnderscore.Identifier);
         expected = "my-5fproject-toolbox";
         testCase.verifyEqual(returned, expected)

         returned = string(optsDot.Identifier);
         expected = "my-2eproject-toolbox";
         testCase.verifyEqual(returned, expected)

         % Determinism: the same name always encodes the same way.
         optsAgain = tbx.internal.releaseoptions( ...
            makeRoot("copy2/my_project"));
         testCase.verifyEqual(string(optsAgain.Identifier), ...
            string(optsUnderscore.Identifier))

         returned = string(optsUnderscore.ToolboxVersion);
         expected = "9.9.9";
         testCase.verifyEqual(returned, expected)
      end
   end
end

function encoded = encodeExpected(name)
   %ENCODEEXPECTED The documented injective identifier encoding.
   %
   % Mirrors the contract releaseoptions documents (letters and digits
   % pass, "-" doubles, others become "-" plus two lowercase hex), so
   % the stamped-generic test pins the contract rather than one
   % hard-coded name.

   arguments
      name (1,1) string
   end

   chars = char(name);
   parts = strings(1, numel(chars));
   for k = 1:numel(chars)
      c = chars(k);
      if ismember(c, ['A':'Z', 'a':'z', '0':'9'])
         parts(k) = string(c);
      elseif c == '-'
         parts(k) = "--";
      else
         parts(k) = "-" + lower(string(dec2hex(double(c), 2)));
      end
   end
   encoded = join(parts, "");
end

function root = makeFallbackRoot(parentFolder, name)
   %MAKEFALLBACKROOT Build a minimal fallback-shaped project fixture.
   %
   % Creates <parentFolder>/<name> with a toolbox/ folder holding one
   % function and a version.txt pinned to v9.9.9, the smallest tree
   % the folder-construction fallback reads. NAME may contain a
   % subfolder (for example "copy2/my_project") to place two fixtures
   % with the same leaf name.

   arguments
      parentFolder (1,1) string
      name (1,1) string
   end

   root = fullfile(parentFolder, name);
   mkdir(fullfile(root, "toolbox"))
   writelines("function y = fx_fun(x), y = x; end", ...
      fullfile(root, "toolbox", "fx_fun.m"));
   writelines("v9.9.9", fullfile(root, "toolbox", "version.txt"));
end
